### ISSUE TITLE
Python 3.7.x/3.8.x: "module typing has no attribute IO"

### ISSUE THREAD

**Issue by dylmye** [agronholm/sphinx-autodoc-typehints#114]
[As requested](https://github.com/agronholm/sphinx-autodoc-typehints/issues/113#issuecomment-547453844)

Tested on 3.7.2, 3.7.3, 3.8, Windows 10 x64. Downgrading the typehints package to 1.8.0 fixed this issue.

Running `make html` in [this project](https://github.com/sedders123/phial/tree/develop/docs) causes the following issue:

```
Exception occurred:
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'IO'>'
```

<details><summary>Full Traceback</summary>
<pre><code>
# Sphinx version: 2.2.1
# Python version: 3.8.0 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   loading intersphinx inventory from https://docs.python.org/objects.inv...
#   intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 3 source files that are out of date
#   updating environment:
#   [new config]
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] getting-started
#   reading sources... [ 66%] index
#   reading sources... [100%] phial
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from C:\Python\3.8\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from C:\Python\3.8\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from C:\Python\3.8\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from C:\Python\3.8\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from C:\Python\3.8\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\Python\3.8\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx_autodoc_typehints (unknown version) from C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py
#   sphinx.ext.intersphinx (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.coverage (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\coverage.py
#   sphinx.ext.viewcode (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\viewcode.py
Traceback (most recent call last):
  File "C:\Python\3.8\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "C:\Python\3.8\lib\site-packages\sphinx\application.py", line 346, in build
    self.builder.build_update()
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "C:\Python\3.8\lib\site-packages\sphinx\io.py", line 326, in read_doc
    pub.publish()
  File "C:\Python\3.8\lib\site-packages\docutils\core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\Python\3.8\lib\site-packages\sphinx\io.py", line 114, in read
    self.parse()
  File "C:\Python\3.8\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "C:\Python\3.8\lib\site-packages\sphinx\parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2098, in directive
    return self.run_directive(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 732, in generate
    self.document_members(all_members)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 652, in document_members
    documenter.generate(
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1186, in generate
    return super().generate(more_content=more_content,
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 729, in generate
    self.add_content(more_content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1172, in add_content
    super().add_content(more_content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 471, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 439, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "C:\Python\3.8\lib\site-packages\sphinx\application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "C:\Python\3.8\lib\site-packages\sphinx\events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 364, in process_docstring
    formatted_annotation = format_annotation(
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'IO'>'
</code></pre>
</details>

**Comment by agronholm** [comment]
There seems to be a discrepancy: the traceback complains about `typing.IO`, yet the subject is about `List`. Care to explain?

**Comment by agronholm** [comment]
But `typing.IO` is a thing. Are you sure you don't have a module named `typing` somewhere in your sys.path that might interfere?

**Comment by dylmye** [comment]
I'm not sure, I'll have a look, but nevertheless it is odd that downgrading my version of `sphinx-autodoc-typehints` to 1.8.0 resolves the issue, no?

**Comment by agronholm** [comment]
It probably just triggered the issue due to the new logic.

**Comment by agronholm** [comment]
Just to check: what does the actual annotation look like that trips this problem?

**Comment by agronholm** [comment]
So this is happening because `class_name` is `IO'>`, due to faulty parsing logic. I'm really trying to stretch my imagination to properly parse the module and class names out of the annotation, while still maintaining compatibility with all the various development phases of the `typing` module.
