### ISSUE TITLE
Unexpected indent

### ISSUE THREAD

**Issue by ppwwyyxx** [agronholm/sphinx-autodoc-typehints#129]
I received a stack trace like this when using this project:
```
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 731, in generate
    self.add_content(more_content)
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 470, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 438, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx/application.py", line 447, in emit
    return self.events.emit(event, *args)
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 362, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 217, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/home/XXX/.local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 258, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    @staticmethod
    ^
IndentationError: unexpected indent

```

I think the issue is due to the use of `textwrap.dedent` to dedent code. The function that causes the error look like this:
```
    @staticmethod
    def get(name):
        """
        Args:
            name (str): name of a dataset (e.g. coco_2014_train).

        Returns:
            Metadata: The :class:`Metadata` instance associated with this name,
            or create an empty one if none is available.
        """
        assert len(name)
        if name in MetadataCatalog._NAME_TO_META:
            ret = MetadataCatalog._NAME_TO_META[name]
            # TODO this is for the BC breaking change in D15247032.
            # Remove this in the future.
            if hasattr(ret, "dataset_name"):
                logger = logging.getLogger()
                logger.warning(
                    """
The 'dataset_name' key in metadata is no longer used for
sharing metadata among splits after D15247032! Add
metadata to each split (now called dataset) separately!
                    """
                )
                parent_meta = MetadataCatalog.get(ret.dataset_name).as_dict()
                ret.set(**parent_meta)
            return ret
        else:
            m = MetadataCatalog._NAME_TO_META[name] = Metadata(name=name)
            return m
```

as you can see, the `dedent` function can no longer work for such a codeblock, and therefore fail to dedent the code. This causes `ast.parse` to fail.

**Comment by IceflowRE** [comment]
```
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\sphinx\events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "c:\python39\lib\site-packages\sphinx_autodoc_typehints.py", line 376, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "c:\python39\lib\site-packages\sphinx_autodoc_typehints.py", line 231, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "c:\python39\lib\site-packages\sphinx_autodoc_typehints.py", line 272, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
  File "c:\python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    def retranslateUi(self, MainWindow):
IndentationError: unexpected indent
```

```python
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.action_add_job.setText(QCoreApplication.translate("MainWindow", u"Add...", None))
#if QT_CONFIG(tooltip)
        self.action_add_job.setToolTip(QCoreApplication.translate("MainWindow", u"Add a new job", None))
#endif // QT_CONFIG(tooltip)
```
(Contains the important lines but not the whole file)

**Comment by kylepjohnson** [comment]
Don't know if this helps, but same error arises for me, too, when building locally:

``` python
$ python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v3.4.1
loading translations [en]... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 46 source files that are out of date
updating environment: [new config] 46 added, 0 changed, 0 removed
reading sources... [ 15%] cltk.dependency                                       
Traceback (most recent call last):
  File "/Users/home-dir-name/venv38/lib/python3.8/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/home-dir-name/venv38/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 376, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/Users/home-dir-name/venv38/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 231, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/Users/home-dir-name/venv38/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 272, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    @staticmethod
    ^
IndentationError: unexpected indent
```

Surprisingly, this build fine on readthedocs. No idea why.

**Comment by ppwwyyxx** [comment]
I'm fixing this in #166
