### ISSUE TITLE
Getting an `IndentationError` related specifically to a doc string while building.

### ISSUE THREAD

**Issue by demitri** [agronholm/sphinx-autodoc-typehints#139]
I've encountered a Sphinx bug which I reported [here](https://github.com/sphinx-doc/sphinx/issues/7631), and it was pointed out to me (via the log) that the error was raised by sphinx-autodoc-hints. The report is duplicated below.

I'm getting the following error when trying to build HTML files:

```
/usr/local/anaconda/lib/python3.7/site-packages/sphinx/util/inspect.py:555: RemovedInSphinx40Warning: sphinx.util.inspect.Signature() is deprecated
  RemovedInSphinx40Warning)

Exception occurred:
  File "/usr/local/anaconda/lib/python3.7/site-packages/typed_ast/ast3.py", line 62, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 1
    @classmethod
    ^
IndentationError: unexpected indent
The full traceback has been saved in /var/folders/yp/lf1xdvp165n5xb7hcrwzpngc0000gn/T/sphinx-err-jidws8_h.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

The code that it's getting caught on is this:

```python
	@classmethod
	def fromFITSHeader(cls, fits_header=None, uncertainty=4.848e-6):
		'''
		Factory method to create a region from the provided FITS header; the returned object will be as specific as possible (but probably an ASTPolygon).
		
		:param fits_header: a FITS header (Astropy, fitsio, an array of cards)
		:param uncertainty: defaults to 4.848e-6, an uncertainty of 1 arcsec
		'''
		if fits_header is None:
			raise ValueError("This method requires a 'fits_header' to be set.")

		. . .
```

I am sure the problem is not an indentation error (at least as far as the Python code). When I delete the entire docstring, `make html` works without error. *Any* docstring I add causes the error, even a blank one, e.g.

```
'''

'''
```

The Sphinx log is attached here:
[sphinx-err-gnkuj5m5.log](https://github.com/sphinx-doc/sphinx/files/4596009/sphinx-err-gnkuj5m5.log)

Thanks!

**Comment by amarandon** [comment]
I have a similar issue and I found that the typed_ast package has been installed as a dependency of another package (pylint in my case). typed_ast replaces the ast module of the Python standard library. Apparently here the problem is that this replacement isn't completely transparent to sphinx-autodoc-typehints. I just tried uninstalling this module and it fixes the problem. So for me the workaround is to do this before building the docs:

    pip uninstall --yes typed_ast

**Comment by demitri** [comment]
@amarandon Great find! I created a new issue there linking back to this one. I also note on the home page:

> typed_ast will not be updated to support parsing Python 3.8 and newer. Instead, it is recommended to use the stdlib ast module there, which has been augmented to support extracting type comments and has limited support for parsing older versions of Python 3.

so this will sort itself out in the long run.

**Comment by gvanrossum** [comment]
Something of interest if you want to help debug this: What are the exact values passed to ast.parse() on the line indicated by the traceback?

**Comment by demitri** [comment]
`ast` isn't something I've used directly before, but I read a little on basic usage. I tried to manually parse the file I was stuck on (located [here](https://github.com/demitri/cornish/blob/master/cornish/region/region.py)) but it didn't return an error. I tried to put a breakpoint in the sphinx generation, but now `make html` crashes on something entirely different that I haven't seen before; I don't think it's getting as far as the `ast` issue. Maybe @amarandon can still reproduce this? Sorry I can't be of more help.

**Comment by agronholm** [comment]
I'm currently busy with another project but if someone can figure out how to fix this I could take in a PR for this.

**Comment by demitri** [comment]
I've made a little progress. The "new" error is really the old one. I modified `sphinx_autodoc_typehints.py` to add a few print statements right before where the error occurs. This is in the method `backfill_type_hints`:

```python
    try:
        print("---> ",textwrap.dedent(inspect.getsource(obj)))
        print("===> ", parse_kwargs)
        obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
    except (OSError, TypeError):
        return {}
```

This is the output trace:

```python
--->  @property... [100%] regions                                                                                                              
def astString(self):
	'''
	Return the AST serialization of this object.
	'''
	return str(self.astObject)

===>  {}
--->  def boundaryPointMesh(self, npoints=None):
	'''
	Returns an array of evenly distributed points that cover the boundary of the region.
	For example, if the region is a box, it will generate a list of points that trace the edges of the box.

	The default value of 'npoints' is 200 for 2D regions and 2000 for three or more dimensions.

	@param npoints The approximate number of points to generate in the mesh.
	@returns List of points.
	'''
	# The starlink.AST object uses the attribute "MeshSize" to determine the number of points to
	# use. This should be specified when building the mesh - the attribute doesn't seem to be used
	# anywhere else. This method shouldn't change the value in case that's not true, but we'll make
	# this one step here.

	if npoints is not None and not isinstance(npoints, int):
		raise Exception("The parameter 'npoints' must be an integer ('{1}' provided).".format(npoints))

	if npoints is None:
		pass # use default meshSize value
	else:
		# use provided value
		#old_mesh_size = self.astObject.get("MeshSize")
		#self.astObject.set("MeshSize={0}".format(npoints))
		old_mesh_size = self.meshSize
		self.meshSize = npoints

	try:
		mesh = self.astObject.getregionmesh(1) # surface=1, here "surface" means the boundary
	except Ast.MBBNF as e:
		print("AST error: Mapping bounding box not found. ({0})".format(e))
		raise e

	if npoints is not None:
		# restore original value
		self.astObject.meshSize = old_mesh_size #self.astObject.set("MeshSize={0}".format(old_mesh_size))

	return mesh.T # returns as a list of pairs of points, not two parallel arrays

===>  {}
--->  def boundingBox(self):
	'''

	'''
	raise NotImplementedError()

===>  {}
--->  def boundingCircle(self):
	'''
	Returns the smallest circle (ASTCircle) that bounds this region.

	It is up to the caller to know that this is a 2D region (only minimal checks are made).
	:raises cornish.exc.NotA2DRegion: raised when attempting to get a bounding circle for a region that is not 2D
	'''

	if self.naxes != 2:
		raise NotA2DRegion(f"A bounding circle can only be computed on a 2D region; this region has {self.naxes} axes.")

	from .circle import ASTCircle
	centre, radius = self.astObject.getregiondisc() # returns radians
	return ASTCircle(frame=self, center=np.rad2deg(centre), radius=rad2deg(radius))

===>  {}
--->  def bounds(self):
	'''
	Return the upper and lower bounds of a box that contains this regions.
	'''

	lower_bounds, upper_bounds = self.astObject.getregionbounds()

===>  {}
--->  def distance(self, point1, point2):
	'''
	Distance between two points in this frame.

	Parameters
	----------
	point1 : list
		A two element list/tuple/Numpy array of the first point coordinates.
	point2 : list
		A two element list/tuple/Numpy array of the second point coordinates.

	Returns
	-------
	float, distance between two provided points
	'''
	return self.astObject.distance(point1, point2)

===>  {}
--->  @property
def domain(self):
	'''
	The physical domain of the coordinate system (string value).
	The Domain attribute also controls how Frames align with each other.
	If the Domain value in a Frame is set, then only Frames with the same Domain value can be aligned with it.

	Example values: GRID, FRACTION, PIXEL, AXIS, SKY, SPECTRUM, CURPIC, NDC, BASEPIC, GRAPHICS

	Frames created by the user (for instance, using WCSADD) can have any Domain value, but the standard
	domain names should be avoided unless the standard meanings are appropriate for the Frame being created.
	'''
	return self.astObject.get("Domain")

===>  {}
--->  @property
def fillFactor(self):
	''' <Fraction of the Region which is of interest> '''
	# TODO: properly document, see p. 812 of documentation
	return self.astObject.get("FillFactor")

===>  {}
--->  def frame(self): # -> ASTFrame:
	'''
	Returns a copy of the frame encapsulated by this region.
	'''
	ast_frame = self.astObject.getregionframe()
	return ASTFrame.frameFromAstObject(ast_frame)

===>  {}
--->  @staticmethod
def frameFromAstObject(ast_object=None):
	'''
	Factory method that returns the appropriate Cornish frame object (e.g. ASTSkyFrame) for a given frame.
	'''
	if ast_object is None:
		raise ValueError("An ast_object must be specified.")
	elif not isinstance(ast_object, Ast.Frame):
		raise Exception(f"Expected 'ast_object' to be some kind of Ast frame, but got {type(ast_object)}")

	# the order might need to be rearranged depending on the object hierarchy

	if isinstance(ast_object, Ast.SkyFrame):
		return ASTSkyFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.SpecFrame):
		return ASTSpecFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.TimeFrame):
		return ASTTimeFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.CmpFrame):
		return ASTCompositeFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.FluxFrame):
		return ASTFluxFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.SpecFluxFrame):
		return ASTSpecFluxFrame(ast_object=ast_object)
	elif isinstance(ast_object, Ast.TimeFrame):
		return ASTTimeFrame(ast_object=ast_object)
	else:
		return ASTFrame(ast_object=ast_object)

===>  {}
--->  def frameSet(self):
	'''
	Returns a copy of the frameset encapsulated by this region.

	From AST docs:
	> The base Frame is the Frame in which the box was originally defined,
	> and the current Frame is the Frame into which the Region is currently mapped
	> (i.e. it will be the same as the Frame returned by astGetRegionFrame).
	'''
	raise NotImplementedError("getregionframeset() has not yet been exposed to the Python interface.")
	return ASTFrameSet(ast_object=self.astObject.getregionframeset())

===>  {}
--->  def framesetWithMappingTo(self, template_frame=None): # maybe think of better name?!
	'''
	Searches 
	:param template_frame:
	:returns: ... , None if no mapping can be found
	'''
	from .frame_set import ASTFrameSet
	if template_frame is None:
		raise ValueError("A template frame must be provided.")
	return ASTFrameSet(ast_object=self.astObject.findframe(template_frame.astObject))

===>  {}
--->  	@classmethod
	def fromFITSHeader(cls, fits_header=None, uncertainty=4.848e-6):
		'''
		Factory method to create a region from the provided FITS header; the returned object will be as specific as possible (but probably an ASTPolygon).

		:param fits_header: a FITS header (Astropy, fitsio, an array of cards)
		:param uncertainty: defaults to 4.848e-6, an uncertainty of 1 arcsec
		'''
		if fits_header is None:
			raise ValueError("This method requires a 'fits_header' to be set.")

		# import here to avoid circular imports
		from .box import ASTBox
		from .circle import ASTCircle
		from .polygon import ASTPolygon
		from ..channel import ASTFITSChannel

		# get frame from header
		fits_channel = ASTFITSChannel(header=fits_header)

		# does this channel contain a frame set?
		frame_set = fits_channel.frameSet
		if frame_set is None:
			raise ValueError("The provided FITS header does not describe a region (e.g. not an image, does not contain a WCS that AST can read).")

		frame = frame_set.baseFrame

		# support n-dimensional regions

		# define needed parameters for region creation below
		dimensions = fits_channel.dimensions
		n_dim = len(dimensions)
		cornerPoint = [0.5 for x in range(n_dim)]
		cornerPoint2 = [dimensions[x] + 0.5 for x in range(n_dim)]
		#cornerPoint=[0.5,0.5], # center of lower left pixel
		#cornerPoint2=[dimensions[0]+0.5, dimensions[1]+0.5])

		if n_dim > 2:
			raise NotImplementedError("HDUs describing dimensions greater than 2 not currently supported.")

		#if isinstance(frame, ASTFrame):
		#	self.frame = frame
		#elif isinstance(frame, starlink.Ast.Frame):
		#	self.frame = ASTFrame(frame=frame)
		#else:
		#	raise Exception("ASTBox: unexpected frame type specified ('{0}').".format(type(frame)))

# 		if all([cornerPoint,centerPoint]) or all([cornerPoint,cornerPoint2]) or dimensions is not None:
# 			if dimensions is not None:
# 				input_form = CORNER_CORNER
# 				p1 = [0.5,0.5] # use 0.5 to specify the center of each pixel
# 				p2 = [dimensions[0]+0.5, dimensions[1]+0.5]
# 			elif centerPoint is None:
# 				input_form = CORNER_CORNER
# 				p1 = [cornerPoint[0], cornerPoint[1]]
# 				p2 = [cornerPoint2[0], cornerPoint2[1]]
# 				dimensions = [math.fabs(cornerPoint[0] - cornerPoint2[0]),
# 							  math.fabs(cornerPoint[1] - cornerPoint2[1])]
# 			else:
# 				input_form = CENTER_CORNER
# 				p1 = [centerPoint[0], centerPoint[1]]
# 				p2 = [cornerPoint[0], cornerPoint[1]]
# 				dimensions = [2.0 * math.fabs(centerPoint[0] - cornerPoint[0]),
# 							  2.0 * math.fabs(centerPoint[1] - cornerPoint[1])]

		# input_form constants (define properly elsewhere?)
		CENTER_CORNER = 0
		CORNER_CORNER = 1

		input_form = CORNER_CORNER
		p1 = [cornerPoint[0], cornerPoint[1]]
		p2 = [cornerPoint2[0], cornerPoint2[1]]
		dimensions = [math.fabs(cornerPoint[0] - cornerPoint2[0]),
					  math.fabs(cornerPoint[1] - cornerPoint2[1])]


		#dimensions = [dimensions[0], dimensions[1]]
		#logger.debug("Setting dims: {0}".format(self.dimensions))

		ast_object = Ast.Box( frame.astObject, input_form, p1, p2, unc=uncertainty )

		# create the mapping from pixel to sky (or whatever is there) if available
		mapping = frame_set.astObject.getmapping() # defaults are good
		current_frame = frame_set.astObject.getframe(starlink.Ast.CURRENT)

		# create a new region with new mapping
		ast_object = ast_object.mapregion(mapping, current_frame)

		if isinstance(ast_object, Ast.Box):
			return ASTBox(ast_object=ast_object)
		elif isinstance(ast_object, Ast.Circle):
			return ASTCircle(ast_object=ast_object)
		elif isinstance(ast_object, Ast.Polygon):
			return ASTPolygon(ast_object=ast_object)
		else:
			raise Exception(f"Unexpected region type encountered: {type(ast_object)}.")

===>  {}
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 367, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 219, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 263, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
  File "/usr/local/anaconda/lib/python3.7/site-packages/typed_ast/ast3.py", line 62, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 1
    @classmethod
    ^
IndentationError: unexpected indent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/anaconda/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1516, in generate
    all_members=all_members)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 846, in generate
    self.document_members(all_members)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1505, in document_members
    super().document_members(all_members)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 729, in document_members
    check_module=members_check_module and not isattr)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 843, in generate
    self.add_content(more_content)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 520, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 487, in process_doc
    self.options, docstringlines)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/application.py", line 450, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/usr/local/anaconda/lib/python3.7/site-packages/sphinx/events.py", line 118, in emit
    (listener.handler, name)) from exc
sphinx.errors.ExtensionError: Handler <function process_docstring at 0x7f9e185aeb00> for event 'autodoc-process-docstring' threw an exception
> /usr/local/anaconda/lib/python3.7/site-packages/sphinx/events.py(118)emit()
-> (listener.handler, name)) from exc
(Pdb)
```

The thing that jumps out is the last block that is indeed indented further than the other blocks, although this is not the case in the file. Maybe the `textwrap.dedent` is the culprit here?

**Comment by gvanrossum** [comment]
Yeah, I think this is because of the unindented comment block in the middle of the method. Because of that, textwrap.dedent() doesn't have the desired effect, so the "dedented" source still starts with a tab character. No Python parser should like this, so I'm not quite sure why you didn't get this error when using the regular ast module -- but quite possibly Sphinx takes a different path there.

I'm going to close the typed_ast bug.

**Comment by demitri** [comment]
I fixed the indentation; works perfectly. `@classmethod` was a red herring! Thanks for the help.

**Comment by agronholm** [comment]
Wait, what was the problem in the end?

**Comment by demitri** [comment]
If you look at my code above, there is a large block of commented code in the last method; see the lines containing `#` at the start of the line with no indentation. I only had to indent the commented lines in line with the rest of the code, and it worked. Do you have something similar?

**Comment by agronholm** [comment]
No, but this problem was first reported in #129, so it really needs fixing.

**Comment by demitri** [comment]
The code in that example shows the same issue - three lines that begin at the start of the line. Agreed, that is a valid Python construct, but that is what appears to be causing `textwrap.dedent` to be confused. Whether this is an issue to be created in that code is another question. It seems reasonable for `dedent` to ignore `#` comments and take into account triple quoted strings.

I think the two possible solutions here are to create an issue in `textwrap` or else have `sphinx-autodoc-typehints` detect this and produce a better error message.

**Comment by gvanrossum** [comment]
This can't be fixed in textwrap.dedent() -- that function doesn't know it's
handling Python source code. Calling it was a shortcut (a hack, even) and
you're simply bumping up to a limitation of that shortcut.

**Comment by agronholm** [comment]
I suspected as much.

**Comment by demitri** [comment]
That's fair. I'd suggest a try/except on `IndentationError` in the sphinx-autodoc-typehints code to re-raise the error and add an additional note to check for the cases noted above as the simplest "fix".
