### ISSUE TITLE
IO type causes stacktrace

### ISSUE THREAD

**Issue by atagar** [agronholm/sphinx-autodoc-typehints#142]
The following method signature...

`def my_method(file_handle: Optional[IO[bytes]] = None):`

Caused sphinx-autodoc-typehints to stacktrace with...

```
# Sphinx version: 3.0.3
# Python version: 3.7.0 (CPython)
# Docutils version: 0.16 release
...
Traceback (most recent call last):
  ...
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx/application.py", line 445, in emit
    return self.events.emit(event, *args)
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 371, in process_docstring
    annotation, fully_qualified=app.config.typehints_fully_qualified)
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 143, in format_annotation
    for arg in args))
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 143, in <genexpr>
    for arg in args))
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 113, in format_annotation
    args = get_annotation_args(annotation, module, class_name)
  File "/home/atagar/.local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 63, in get_annotation_args
    original = getattr(sys.modules[module], class_name)
TypeError: getattr(): attribute name must be string
```

Changing the IO[bytes] to another type (like BinaryIO) avoids this. If I add a print statement get_annotation_args provides...

`annotation: typing.IO[bytes], module: typing, class_name: <abc.abstractproperty object at 0x7fae1e1ba768>`

Expanding the method's exception catch to include TypeErrors could be a simple short term workaround.

**Comment by JamesALeedham** [comment]
Is the problem here the 'list inside the list' for the type hint?

I get this when trying to document a package - too many instances of this pattern to track it down or eradicate it though.

I added `TypeError` to the list of exceptions caught for `get_annotation_args`, as suggested by @atagar above (thanks!), then followed the errors to add `TypeError` and `UnboundLocalError` catches to various other places in `/site-packages/sphinx_autodoc_typehints.py` - eventually I got the documentation to compile.

A pain though. Is there a fix?
