### ISSUE TITLE
False positive warning (?)

### ISSUE THREAD

**Issue by A5rocks** [agronholm/sphinx-autodoc-typehints#163]
Either this is a false positive, or evaluation of generated code's forward references is broken -- I really hope it's the former.

Minimal case:
`repro.py`:
```py
from __future__ import annotations

import attr
import typing

@attr.s(auto_attribs=True)
class Example:
    blah: typing.Type[int]
```

Console output:
```
...
WARNING: Cannot resolve forward reference in type annotations of "repro.Example": name 'typing' is not defined
...
```

~~However, the docs still render alright (?) and if you use intersphinx it does work... So, mixed feelings from this.~~ I may have messed up with browser cache or something, try this out and see for yourself.

Note that you can either comment out `@attr.s(auto_attribs=True)`, remove `auto_attribs=True` (for some reason?), or comment out `from __future__ import annotations` to get rid of this warning.

I'm new to this whole documentation thing, so I may have missed something though.

**Comment by A5rocks** [comment]
More info:
 - You *can* `typing.get_type_hints` from another module, here's an example of how:
 ```py
from __init__ import Example
from typing import get_type_hints

print(get_type_hints(Example))
```

 - Stack trace:
 ```
 Traceback (most recent call last):
  File "C:\Users\A5rocks\Documents\fun\python-tests\docs\source\sphinx_autodoc_typehints.py", line 230, in get_all_type_hints
    rv = get_type_hints(obj)
  File "C:\Python39\lib\typing.py", line 1442, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "C:\Python39\lib\typing.py", line 277, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Python39\lib\typing.py", line 533, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'typing' is not defined
 ```

I cannot think of a reason why this would work in one context and not in another....
