### ISSUE TITLE
Annotation with metaclass leads to "TypeError: descriptor 'mro' of 'type' object needs an argument"

### ISSUE THREAD

**Issue by K0Te** [agronholm/sphinx-autodoc-typehints#73]
Any annotation with Django's `ModelBase` leads to following exception:
```
Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 129, in format_annotation
    mro = annotation_cls.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument
The full traceback has been saved in /tmp/sphinx-err-3opwt0gy.log, if you want to report the issue to the developers.
```

Full log:
```
root@35afc9235751:/code# cat /tmp/sphinx-err-3opwt0gy.log
# Sphinx version: 1.8.4
# Python version: 3.7.0 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   
#   building [html]: targets for 45 source files that are out of date
#   
#   updating environment:
#   
#   45 added, 0 changed, 0 removed
#   
#   reading sources... [  2%] gulfstream
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from /usr/local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /usr/local/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.4) from /usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx_autodoc_typehints (unknown version) from /usr/local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py
#   sphinx.ext.todo (1.8.4) from /usr/local/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.8.4) from /usr/local/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.viewcode (1.8.4) from /usr/local/lib/python3.7/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.7/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 131, in run
    documenter.generate(more_content=self.content)
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 819, in generate
    self.document_members(all_members)
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 740, in document_members
    check_module=members_check_module and not isattr)
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 816, in generate
    self.add_content(more_content)
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 554, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 514, in process_doc
    self.options, docstringlines)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python3.7/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 209, in process_docstring
    formatted_annotation = format_annotation(annotation)
  File "/usr/local/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 129, in format_annotation
    mro = annotation_cls.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument
```

**Comment by erickpeirson** [comment]
Not sure whether this is a bug, or a misreading of PEP484 on my part, or an edge case not covered by PEP484, or...what. 

The problem: if a type annotation is a metaclass (i.e. inherits from ``type``), sphinx-autodoc-typehints chokes with.

```
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 129, in format_annotation
    mro = annotation_cls.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument
```

The offending line is: https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L129

Here is a minimal example that will trigger this exception:

```python
class MyMeta(type):
    pass


class MyClass(metaclass=MyMeta):
    pass


def something_with_a_class(klass: type) -> None:    # No problem.
    """Do something with a class."""
    pass


def something_meta(klass: MyMeta) -> None:    # Triggers exception.
    """Do something with a class with a metaclass."""
    pass
```

On cursory reading, it appears that the metaclass case is only handled if the annotation class is a ``typing.Type`` which, in the example above, ``MyMeta`` is not.

```python
if annotation_cls.__module__ == 'typing':    #L46
    if inspect.isclass(getattr(annotation, '__origin__', None)):    # L52
        annotation_cls = annotation.__origin__ .   # L53
        try:    # L54
            mro = annotation_cls.mro() .   # L55
        except TypeError:    # L58
            pass  # annotation_cls was either the "type" object or typing.Type .   # L59
```

PEP484 [discusses](https://www.python.org/dev/peps/pep-0484/#the-type-of-class-objects) the case in which an annotation refers to the "type" of a particular class, e.g. if we have a function that accepts a particular class or a family of classes with a particular parent class. For example:

```python
from typing import Type


class Parent:
    pass


class Child(Parent):
    pass


class GrandChild(Child):
    pass


def do_something_transitive(klass: Type[Parent]) -> None:
    pass
```

But this does not help much when we are dealing not with a family of classes with a common ancestor, but a collection of classes with a common metaclass. I would (perhaps naively) expect an annotation that is a metaclass to work, since (in the first example) ``type(MyClass) is MyMeta``. Also, using ``type`` as an annotation does not cause problems, as shown above.

For what it's worth, ``mypy`` does not seem to have a problem with the metaclass example. Not that this should be an absolute guide.

A fix for this might be to catch the TypeError at L129 and just skip https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L130-L134.

```
Name: sphinx-autodoc-typehints
Version: 1.6.0
Summary: Type hints (PEP 484) support for the Sphinx autodoc extension
```

**Comment by wouter-vdb** [comment]
FYI: My [fix](https://github.com/wouter-vdb/sphinx-autodoc-typehints/commit/0470e1b27dbc53bcf93b73a5e06077b2dda1d3a3) solves my case in which the return value of a decorator function was annotated as `Callable[[Foo], Foo]` where `Foo` is a meta-class.

**Comment by daniel-raimi-zlatic** [comment]
@wouter-vdb is your fix merged into v1.8.0? I am running into the same issue, even after your fix. My minimal example is pretty much the exact same as yours, and the associated error is given below. I use metaclasses a lot, so a full fix is appreciated. I'm not sure I understand your workaround of using typing.Type[Parent]. Thank you! 

`class MetaClass(type):
    """Some docstring about MetaClass"""
    pass


def some_function(cls: MetaClass):
    """

    :param cls: Some docstring about cls
    :return: Some docstring about mro
    """
    return "hello"


class Class(metaclass=MetaClass):
    """Some docstring about Class"""
    pass


cls_mro = some_function(cls=Class)
print(cls_mro)`

And the error is:

# Sphinx version: 2.2.0
# Python version: 3.7.3 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   Running Sphinx v2.2.0
#   loading translations [en]...
#   done
#   loading pickled environment...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 0 source files that are out of date
#   updating environment:
#   0 added, 1 changed, 0 removed
#   reading sources... [100%] index
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (2.2.0) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx_autodoc_typehints (unknown version) from c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx_autodoc_typehints.py
Traceback (most recent call last):
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\application.py", line 346, in build
    self.builder.build_update()
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\io.py", line 326, in read_doc
    pub.publish()
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\io.py", line 114, in read
    self.parse()
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 171, in run
    input_source=document['source'])
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\docutils\parsers\rst\states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 732, in generate
    self.document_members(all_members)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 654, in document_members
    check_module=members_check_module and not isattr)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 729, in generate
    self.add_content(more_content)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 471, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 441, in process_doc
    self.options, docstringlines)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx\events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx_autodoc_typehints.py", line 359, in process_docstring
    annotation, fully_qualified=app.config.typehints_fully_qualified)
  File "c:\users\raimidi1\documents\libraries\sandbox\sandbox-venv\lib\site-packages\sphinx_autodoc_typehints.py", line 121, in format_annotation
    mro = annotation_cls.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument

**Comment by agronholm** [comment]
`type.mro()` would bail on the same error so how can it work while a metaclass won't?

**Comment by agronholm** [comment]
Answering my own question: because it gets special cased on line 21.

**Comment by agronholm** [comment]
Fix complete, just need to merge with the code from the latest PR.

**Comment by daniel-raimi-zlatic** [comment]
@agronholm Thanks! When you say "Fix complete", do you mean that my issue is resolved in your branch you just created, but not previously?

**Comment by agronholm** [comment]
I have a fix made locally here, I am just in the process of merging it with a PR I merged to master previously so I can push the fix to master.
