### ISSUE TITLE
Regression from #87

### ISSUE THREAD

**Issue by wkschwartz** [agronholm/sphinx-autodoc-typehints#90]
#87 via 1599287cbfa4 caused a regression that broke my build (traceback below the fold). The issue is https://github.com/agronholm/sphinx-autodoc-typehints/blob/5a0cda7bed875f31e69ce3e59d761513a537e1c7/sphinx_autodoc_typehints.py#L208

when `obj` is a built in type, such as `str`

I'm not sure what type signature in my code base caused the error because I can't tell from the traceback. Sorry I don't have a minimal working example.

<details>

This occurred with sphinx-autodoc-typehints version 1.7.0.

```python-traceback
$ python setup.py build_docs
running build_docs
Running Sphinx v2.1.2
loading pickled environment... failed
failed: No such config value: typehints_fully_qualified
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                           
Exception occurred:
  File "/.../venv/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 208, in get_all_type_hints
    obj.__annotations__ = rv
TypeError: can't set attributes of built-in/extension type 'str'
The full traceback has been saved in /.../sphinx-err-1ncbgg0s.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

And this is the log file mentioned above:
```python-traceback
# Sphinx version: 2.1.2
# Python version: 3.7.3 (CPython)
# Docutils version: 0.15 release
# Jinja2 version: 2.10.1
# Last messages:
#   Running Sphinx v2.1.2
#   loading pickled environment...
#   failed
#   failed: No such config value: typehints_fully_qualified
#   loading intersphinx inventory from https://docs.python.org/3/objects.inv...
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 1 source files that are out of date
#   updating environment:
#   1 added, 0 changed, 0 removed
#   reading sources... [100%] index
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.2) from /.../venv/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /.../venv/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /.../venv/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /.../venv/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /.../venv/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /.../venv/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /.../venv/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.1.2) from /.../venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (2.1.2) from /.../venv/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx_autodoc_typehints (unknown version) from /.../venv/lib/python3.7/site-packages/sphinx_autodoc_typehints.py
Traceback (most recent call last):
  File "/.../venv/lib/python3.7/site-packages/sphinx/setup_command.py", line 193, in run
    app.build(force_all=self.all_files)
  File "/.../venv/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/.../venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/.../venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/.../venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/.../venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/.../venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/.../venv/lib/python3.7/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/.../venv/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/.../venv/lib/python3.7/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/.../venv/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/.../venv/lib/python3.7/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/.../venv/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/.../venv/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/.../venv/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 150, in run
    documenter.generate(more_content=self.content)
  File "/.../venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 757, in generate
    self.add_content(more_content)
  File "/.../venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 484, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/.../venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 463, in process_doc
    self.options, docstringlines)
  File "/.../venv/lib/python3.7/site-packages/sphinx/application.py", line 449, in emit
    return self.events.emit(event, *args)
  File "/.../venv/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/.../venv/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 303, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/.../venv/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 208, in get_all_type_hints
    obj.__annotations__ = rv
TypeError: can't set attributes of built-in/extension type 'str'
```
</details>

**Comment by agronholm** [comment]
Yeah, I was kind of afraid this would happen. I will remove the code that sets the annotations.

**Comment by agronholm** [comment]
Rather, I will have it handle `TypeError` as well.

**Comment by agronholm** [comment]
Would you mind testing the fix from the `regrfix` branch?

**Comment by agronholm** [comment]
@wkschwartz you haven't responded in a while – do you still need help with this?

**Comment by wkschwartz** [comment]
Sorry, currently under water with other work at the moment. I'll take a look at this eventually but don't wait for me if you can fix it yourself as I could be awhile.

**Comment by agronholm** [comment]
I need your help because I do not know how to reproduce the problem you reported.
